monolog:
    channels:
        - default
        - slack

    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: ["!event, !issue"]

        issue:
            type: stream
            path: "%kernel.logs_dir%/issue.log"
            level: debug
            channels: ["issue"]

        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        slack:
            type: slack
            token: '%env(SLACK_TOKEN)%'
            channel: '%env(SLACK_CHANNEL)%'
            channels: ['slack']
