services:

  Bundles\GoogleTaskBundle\Service\TaskSender:
    arguments:
      - '@router'
      - '@kernel'
      - '@Bundles\GoogleTaskBundle\Bag\TaskBag'

  Bundles\GoogleTaskBundle\Service\TaskReceiver:
    arguments:
      - '@Bundles\GoogleTaskBundle\Bag\TaskBag'
