services:

  Bundles\TwilioBundle\Controller\CallController:
    arguments:
      - '@request_stack'
      - '@Bundles\TwilioBundle\Manager\TwilioCallManager'
      - '@logger'
    tags:
      - controller.service_arguments

  Bundles\TwilioBundle\Controller\MessageController:
    arguments:
      - '@request_stack'
      - '@Bundles\TwilioBundle\Manager\TwilioMessageManager'
      - '@logger'
    tags:
      - controller.service_arguments

  Bundles\TwilioBundle\Controller\StatusController:
    arguments:
      - '@request_stack'
      - '@Bundles\TwilioBundle\Manager\TwilioMessageManager'
      - '@Bundles\TwilioBundle\Manager\TwilioStatusManager'
      - '@event_dispatcher'
      - '@logger'
    tags:
      - controller.service_arguments
