# Cron file for App Engine
cron:
  # 0 0 * * * <path/to/the/project>/symfony/bin/console user:cron --env=prod
  - description: "Clears up non activated accounts and expired captcha whitelists"
    url: /cron/user-cron
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console campaign:expired
  - description: "Automatically close inactive campaigns"
    url: /cron/campaign-expired
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console pegass
  - description: "Maintain Pegass cache"
    url: /cron/pegass
    schedule: every 1 minutes

  # * * * * * <path/to/the/project>/symfony/bin/console twilio:price
  - description: "Fetch missing message prices on Twilio"
    url: /cron/twilio-price
    schedule: every 1 hours

  # * * * * * <path/to/the/project>/symfony/bin/console media:clear
  - description: "Remove epxired medias"
    url: /cron/media-clear
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console space:clear
  - description: "Remove epxired volunteer space sessions"
    url: /cron/space-clear
    schedule: every 24 hours
