services:

  Bundles\ApiBundle\Manager\TokenManager:
    arguments:
      - '@Bundles\ApiBundle\Repository\TokenRepository'

  Bundles\ApiBundle\Manager\TokenLogManager:
    arguments:
      - '@Bundles\ApiBundle\Repository\TokenLogRepository'
