openapi: 3.0.2
info:
  description: >-
    This API describes the contract between Tasks and RedCall in the
    following flow: Webhooks -> Cloud Functions -> Tasks -> RedCall
  version: 0.0.1
  title: Controlled RedCall inbound webhooks
  termsOfService: ''
  contact:
    email: minutis@blablacar.com
servers:
  - url: 'https://dev.redcall.minutis.croix-rouge.fr'
    description: Preproduction server
components:
  schemas:
    WebhookRequest:
      type: "object"
      properties:
        uri:
          type: "string"
          description: "Absolute Cloud Function request URI"
        queryParams:
          type: "object"
          description: "The parameters passed in the URL"
          additionalProperties:
            type: string
        headers:
          type: "object"
          description: "Headers attached the the Cloud Function request"
          additionalProperties:
            type: string
        method:
          type: "string"
          description: "the http method used by twilio to call the CF"
        body:
          type: "string"
          description: "JSON representation of the Cloud Function request body"
        origin:
          type: "string"
          description: "The origin of the request (sms status: 'webhook-sms-status', sms response : 'webhook-sms-responses'"
tags:
  - name: endpoints
    description: Available endpoints
paths:
  '/task/webhooks':
    post:
      tags:
        - endpoints
      summary: 'Forward webhooks to RedCall'
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '204':
          description: "No Content"
